// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdpqz-kD3IJLb01kyXoC80sBW0f2zUpz8',
    appId: '1:1067690827652:web:360b56b9d484659d9cc7d1',
    messagingSenderId: '1067690827652',
    projectId: 'egg-incubation-app',
    authDomain: 'egg-incubation-app.firebaseapp.com',
    databaseURL: 'https://egg-incubation-app-default-rtdb.firebaseio.com',
    storageBucket: 'egg-incubation-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvEthX97Xi_oEUVa1xZAIgQxLb4kZOnM',
    appId: '1:1067690827652:android:a73264223c26ccbc9cc7d1',
    messagingSenderId: '1067690827652',
    projectId: 'egg-incubation-app',
    databaseURL: 'https://egg-incubation-app-default-rtdb.firebaseio.com',
    storageBucket: 'egg-incubation-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpsAycmkcukHwyn0KOhR5EA8TOsWY7Q9w',
    appId: '1:1067690827652:ios:beed5b463cc652079cc7d1',
    messagingSenderId: '1067690827652',
    projectId: 'egg-incubation-app',
    databaseURL: 'https://egg-incubation-app-default-rtdb.firebaseio.com',
    storageBucket: 'egg-incubation-app.appspot.com',
    iosClientId: '1067690827652-f293eoadujt26e01vnm3l1g8d3ul0iof.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpsAycmkcukHwyn0KOhR5EA8TOsWY7Q9w',
    appId: '1:1067690827652:ios:beed5b463cc652079cc7d1',
    messagingSenderId: '1067690827652',
    projectId: 'egg-incubation-app',
    databaseURL: 'https://egg-incubation-app-default-rtdb.firebaseio.com',
    storageBucket: 'egg-incubation-app.appspot.com',
    iosClientId: '1067690827652-f293eoadujt26e01vnm3l1g8d3ul0iof.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );
}
